#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# OpenClaw: Zenith — one-shot Ubuntu/Debian build script.
#
# Installs the JDK + Android SDK (only the bits we need), accepts every SDK
# licence, builds the debug APK with the bundled Gradle wrapper, and stages
# the resulting APK into ./dist/.
#
# Designed to be idempotent: re-running just rebuilds.
#
# Usage:
#     bash setup.sh            # full install + build
#
# Or, from a clean Ubuntu shell, as a single line:
#     git clone https://github.com/Abhishek-Issac/OpenClaw.git \
#       && cd OpenClaw \
#       && bash setup.sh
# -----------------------------------------------------------------------------

set -euo pipefail

# -- Configuration ------------------------------------------------------------
ANDROID_HOME="${ANDROID_HOME:-$HOME/android-sdk}"
ANDROID_SDK_ROOT="$ANDROID_HOME"
JAVA_MIN_MAJOR=17

# Android command-line tools revision. Update this number when bumping to a
# newer cmdline-tools bundle: https://developer.android.com/studio#cmdline-tools
CMDLINE_TOOLS_VERSION="11076708"

SDK_PLATFORM="platforms;android-34"
SDK_BUILD_TOOLS="build-tools;34.0.0"
SDK_PLATFORM_TOOLS="platform-tools"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="$REPO_ROOT/dist"

# -- Logging helpers ----------------------------------------------------------
if [ -t 1 ]; then
    CYAN='\033[1;36m'; YELLOW='\033[1;33m'; RED='\033[1;31m'; RESET='\033[0m'
else
    CYAN=''; YELLOW=''; RED=''; RESET=''
fi
log()   { printf "${CYAN}[OpenClaw setup]${RESET} %s\n" "$*"; }
warn()  { printf "${YELLOW}[OpenClaw setup] %s${RESET}\n" "$*" >&2; }
fatal() { printf "${RED}[OpenClaw setup] %s${RESET}\n" "$*" >&2; exit 1; }

# -- Privilege helper ---------------------------------------------------------
SUDO=""
if [ "$(id -u)" -ne 0 ]; then
    if command -v sudo >/dev/null 2>&1; then
        SUDO="sudo"
    else
        fatal "Not running as root and 'sudo' is not installed."
    fi
fi

require_linux() {
    [ "$(uname -s)" = "Linux" ] || fatal "Only Linux is supported (got $(uname -s))."
}

apt_install() {
    command -v apt-get >/dev/null 2>&1 \
        || fatal "apt-get not found. This script targets Ubuntu/Debian. Install: $*"
    log "Installing apt packages: $*"
    $SUDO apt-get update -qq
    $SUDO DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "$@"
}

ensure_prereqs() {
    local need=()
    command -v curl  >/dev/null 2>&1 || need+=("curl")
    command -v unzip >/dev/null 2>&1 || need+=("unzip")
    command -v git   >/dev/null 2>&1 || need+=("git")
    command -v file  >/dev/null 2>&1 || need+=("file")
    if [ "${#need[@]}" -gt 0 ]; then
        apt_install "${need[@]}"
    fi
}

ensure_java() {
    local major=0
    if command -v java >/dev/null 2>&1; then
        major=$(java -version 2>&1 | head -n1 \
            | sed -E 's/.*"([0-9]+)\.?.*/\1/' \
            | grep -E '^[0-9]+$' || echo 0)
    fi
    if [ "$major" -lt "$JAVA_MIN_MAJOR" ]; then
        apt_install openjdk-17-jdk-headless
        $SUDO update-java-alternatives -s java-1.17.0-openjdk-amd64 2>/dev/null || true
    fi
    if [ -z "${JAVA_HOME:-}" ]; then
        JAVA_HOME="$(dirname "$(dirname "$(readlink -f "$(command -v java)")")")"
        export JAVA_HOME
    fi
    log "Java: $(java -version 2>&1 | head -n1) (JAVA_HOME=$JAVA_HOME)"
}

ensure_android_sdk() {
    mkdir -p "$ANDROID_HOME/cmdline-tools"
    if [ ! -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
        log "Downloading Android command-line tools (rev $CMDLINE_TOOLS_VERSION) -> $ANDROID_HOME"
        local zip="/tmp/android-cmdline-tools-$$.zip"
        local url="https://dl.google.com/android/repository/commandlinetools-linux-${CMDLINE_TOOLS_VERSION}_latest.zip"
        curl -fsSL "$url" -o "$zip"
        rm -rf "$ANDROID_HOME/cmdline-tools/latest"
        unzip -q "$zip" -d "$ANDROID_HOME/cmdline-tools/"
        mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
        rm -f "$zip"
    else
        log "Android cmdline-tools already present, skipping download."
    fi

    export ANDROID_HOME ANDROID_SDK_ROOT
    export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

    log "Accepting SDK licences"
    yes | sdkmanager --licenses >/dev/null 2>&1 || true

    log "Installing: $SDK_PLATFORM_TOOLS, $SDK_PLATFORM, $SDK_BUILD_TOOLS"
    sdkmanager --install "$SDK_PLATFORM_TOOLS" "$SDK_PLATFORM" "$SDK_BUILD_TOOLS" >/dev/null
}

write_local_properties() {
    cat > "$REPO_ROOT/local.properties" <<EOF
# Generated by setup.sh. Do not commit.
sdk.dir=$ANDROID_HOME
EOF
}

build_apk() {
    cd "$REPO_ROOT"
    chmod +x ./gradlew
    log "Running ./gradlew --no-daemon assembleDebug (first run downloads Gradle 8.7 + deps)"
    ./gradlew --no-daemon assembleDebug
}

stage_apk() {
    mkdir -p "$DIST_DIR"
    local src="$REPO_ROOT/app/build/outputs/apk/debug/app-debug.apk"
    [ -f "$src" ] || fatal "Build finished but APK not found at $src"
    local ts
    ts="$(date +%Y%m%d-%H%M%S)"
    local dst="$DIST_DIR/OpenClawZenith-debug-${ts}.apk"
    cp "$src" "$dst"
    cp "$src" "$DIST_DIR/OpenClawZenith-debug.apk"
    log ""
    log "Build complete."
    log "  Timestamped APK: $dst"
    log "  Latest copy:     $DIST_DIR/OpenClawZenith-debug.apk"
    log ""
    log "Install on a connected device with:"
    log "  adb install -r $DIST_DIR/OpenClawZenith-debug.apk"
}

main() {
    require_linux
    ensure_prereqs
    ensure_java
    ensure_android_sdk
    write_local_properties
    build_apk
    stage_apk
}

main "$@"
